services:
  benchlog:
    build: .
    container_name: benchlog
    restart: unless-stopped

    ports:
      - "3010:3001"

    environment:
      PORT: 3001
      DB_PATH: /data/database.db

    volumes:
      - ./data:/data
