import type { KitDefinition } from '@/lib/kitManifest';

export const finishKit: KitDefinition = {
  id: 'finishing',
  label: 'Finishing Kit',
  subKits: ['FINISH'],
  entries: [
    // ── MANUFACTURED / MATERIAL ──────────────────────────────────────

    { partNumber: 'AT6-058X3/8', nomenclature: 'SEAT BELT BUSHING MATERIAL', qtyRequired: 1, partType: 'MATERIAL', material: 'AT6-058X3/8', subKit: 'FINISH' },
    { partNumber: 'AT6-058X5/16', nomenclature: 'SEAT BELT BUSHING MATERIAL', qtyRequired: 1, partType: 'MATERIAL', material: 'AT6-058X5/16', subKit: 'FINISH' },
    { partNumber: 'BUSHING-F-ST.438X.750X1.328', nomenclature: 'BUSHING, FLANGED, STEEL', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1002', nomenclature: 'FILLER GAP FILLER', qtyRequired: 1, partType: 'MATERIAL', material: 'PARABEAM - 8mm 9" x 30"', subKit: 'FINISH' },
    { partNumber: 'C-1002A-L', nomenclature: 'CABIN DOOR OUTER SHELL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'EPOXY PRE-PREG/S-GLASS', subKit: 'FINISH' },
    { partNumber: 'C-1002A-R', nomenclature: 'CABIN DOOR OUTER SHELL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'EPOXY PRE-PREG/S-GLASS', subKit: 'FINISH' },
    { partNumber: 'C-1002B-L', nomenclature: 'CABIN DOOR INNER SHELL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'EPOXY PRE-PREG/S-GLASS', subKit: 'FINISH' },
    { partNumber: 'C-1002B-R', nomenclature: 'CABIN DOOR INNER SHELL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'EPOXY PRE-PREG/S-GLASS', subKit: 'FINISH' },
    { partNumber: 'C-1002C', nomenclature: 'GAS STRUT ATTACH DOUBLER', qtyRequired: 2, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'C-1003-L', nomenclature: 'FRONT WINDOW', qtyRequired: 1, partType: 'MANUFACTURED', material: '.125 ACRYLIC SHEET', subKit: 'FINISH' },
    { partNumber: 'C-1003-R', nomenclature: 'FRONT WINDOW', qtyRequired: 1, partType: 'MANUFACTURED', material: '.125 ACRYLIC SHEET', subKit: 'FINISH' },
    { partNumber: 'C-1006A', nomenclature: 'HANDLE PLATE', qtyRequired: 2, partType: 'MANUFACTURED', material: '.125 2024-T3 ALCLAD', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1006B', nomenclature: 'HANDLE PIVOT', qtyRequired: 2, partType: 'MANUFACTURED', material: '1/8 UHMW PLASTIC', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1006C', nomenclature: 'HANDLE PIVOT', qtyRequired: 2, partType: 'MANUFACTURED', material: '1/2 UHMW PLASTIC', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1006D', nomenclature: 'HANDLE FACE PLATE', qtyRequired: 2, partType: 'MANUFACTURED', material: '304 STAINLESS', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1007', nomenclature: 'HANDLE SLIDE', qtyRequired: 2, partType: 'MANUFACTURED', material: 'ST4130-058 X 3/8', subKit: 'FINISH', bag: 'BAG 1546' },
    { partNumber: 'C-1008', nomenclature: 'HANDLE LEVER', qtyRequired: 2, partType: 'MANUFACTURED', material: '.190 2024-T3 BARE', subKit: 'FINISH' },
    { partNumber: 'C-1009', nomenclature: 'DOOR FWD PIN BLOCK', qtyRequired: 2, partType: 'MANUFACTURED', material: '3/4 UHMW PLASTIC', subKit: 'FINISH', bag: 'BAG 1547' },
    { partNumber: 'C-1010', nomenclature: 'CABIN PIN BLOCK', qtyRequired: 4, partType: 'MANUFACTURED', material: '1/4 UHMW PLASTIC', subKit: 'FINISH', bag: 'BAG 1547' },
    { partNumber: 'C-1011-L', nomenclature: 'FORWARD LATCH PIN', qtyRequired: 1, partType: 'MANUFACTURED', material: 'AT6-065 X 7/16', subKit: 'FINISH' },
    { partNumber: 'C-1011-R', nomenclature: 'FORWARD LATCH PIN', qtyRequired: 1, partType: 'MANUFACTURED', material: 'AT6-065 X 7/16', subKit: 'FINISH' },
    { partNumber: 'C-1012-L', nomenclature: 'AFT LATCH PIN', qtyRequired: 1, partType: 'MANUFACTURED', material: 'AT6-065 X 7/16', subKit: 'FINISH' },
    { partNumber: 'C-1012-R', nomenclature: 'AFT LATCH PIN', qtyRequired: 1, partType: 'MANUFACTURED', material: 'AT6-065 X 7/16', subKit: 'FINISH' },
    { partNumber: 'C-1013', nomenclature: 'GAS STRUT ATTACH BRACKET', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH', bag: 'BAG 1547' },
    { partNumber: 'C-1014', nomenclature: 'HANDLE SPUR GEAR', qtyRequired: 2, partType: 'MANUFACTURED', material: 'SPUR GEAR 1.25 OD', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'C-1015', nomenclature: 'HANDLE SLIDE CAP', qtyRequired: 2, partType: 'MANUFACTURED', material: 'BLACK UHMW', subKit: 'FINISH', bag: 'BAG 1547' },
    { partNumber: 'C-1016', nomenclature: 'GAS STRUT', qtyRequired: 2, partType: 'MANUFACTURED', material: 'STABILUS GAS STRUT', subKit: 'FINISH' },
    { partNumber: 'C-1016B', nomenclature: 'BUSHING', qtyRequired: 4, partType: 'MATERIAL', material: 'AT6-058 X 5/16', subKit: 'FINISH' },
    { partNumber: 'C-1017', nomenclature: 'DOOR AFT PIN BLOCK', qtyRequired: 2, partType: 'MANUFACTURED', material: '3/4 UHMW PLASTIC', subKit: 'FINISH', bag: 'BAG 1547' },
    { partNumber: 'C-1019', nomenclature: 'SAFETY LATCH WEAR PLATE', qtyRequired: 2, partType: 'MANUFACTURED', material: '.0178 304 STAINLESS', subKit: 'FINISH', bag: 'BAG 542' },
    { partNumber: 'C-1020', nomenclature: 'LATCH ATTACH ANGLE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH', bag: 'BAG 543' },
    { partNumber: 'C-1021', nomenclature: 'LATCH DOUBLER ANGLE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'SPRING.032 WIREX18', nomenclature: 'MUSIC WIRE .032 X18" (C-1022)', qtyRequired: 1, partType: 'MATERIAL', material: '.032 MUSIC WIRE', subKit: 'FINISH' },
    { partNumber: 'C-656', nomenclature: 'CANOPY HANDLE', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH', bag: 'BAG 1546' },
    { partNumber: 'CA-10003A-L', nomenclature: 'FRAME, SIDE, SEAT BOTTOM', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003A-R', nomenclature: 'FRAME, SIDE, SEAT BOTTOM', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003B', nomenclature: 'FRAME, CROSS, SEAT BOTTOM', qtyRequired: 4, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003C', nomenclature: 'FRAME, CROSS, SEAT BOTTOM', qtyRequired: 8, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003D', nomenclature: 'PAN, SEAT', qtyRequired: 2, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'CA-10003E', nomenclature: 'SLIDE, SEAT TRACK', qtyRequired: 8, partType: 'MANUFACTURED', material: 'WHITE UHMW', subKit: 'FINISH' },
    { partNumber: 'CA-10003F-L', nomenclature: 'HOUSING, RECLINE', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003F-R', nomenclature: 'HOUSING, RECLINE', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003G', nomenclature: 'COVER, RECLINE HOUSING', qtyRequired: 4, partType: 'MANUFACTURED', material: '.032 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'CA-10003H', nomenclature: 'LOCK, RECLINE', qtyRequired: 4, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'CA-10003J', nomenclature: 'BRACKET, RECLINE', qtyRequired: 4, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'CA-10003K-1', nomenclature: 'WEB, SEAT BACK', qtyRequired: 2, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'CA-10003M', nomenclature: 'SOCKET, RETURN SPRING', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003N', nomenclature: 'HOUSING, SEAT ADJUSTMENT', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH' },
    { partNumber: 'CA-10003P', nomenclature: 'PIN, SEAT ADJUSTMENT', qtyRequired: 2, partType: 'MANUFACTURED', material: '17-4 PH COND A STAINLESS', subKit: 'FINISH', bag: 'BAG 1022' },
    { partNumber: 'CA-10003T', nomenclature: 'CAP, SPRING', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH', bag: 'BAG 1023' },
    { partNumber: 'CA-10003U', nomenclature: 'HANDLE, SEAT ADJUSTMENT', qtyRequired: 2, partType: 'MANUFACTURED', material: '6061-T6', subKit: 'FINISH', bag: 'BAG 1025' },
    { partNumber: 'CA-10003V', nomenclature: 'HANDLE, RECLINE', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'CA-10004A', nomenclature: 'CUSHION, SEAT BOTTOM', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'CA-10004B', nomenclature: 'CUSHION, SEAT BACK', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'CA-10004C', nomenclature: 'CUSHION, HEAD REST', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'CA-10004D', nomenclature: 'CUSHION, LUMBAR SUPPORT', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'COWL, 10 BOT IO-540', nomenclature: 'BOTTOM COWL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'COWL, 10 INLET LEFT', nomenclature: 'INLET RAMP', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'COWL, 10 INLET RIGHT', nomenclature: 'INLET RAMP', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'COWL, 10 TOP IO-540', nomenclature: 'TOP COWL', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'COWL-10-01A', nomenclature: 'OIL DOOR', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'COWL-10-01B', nomenclature: 'OIL DOOR CORE', qtyRequired: 1, partType: 'MANUFACTURED', material: '2 LB. POLYURETHANE FOAM', subKit: 'FINISH' },
    { partNumber: 'COWL-10-02', nomenclature: 'OIL DOOR HINGE', qtyRequired: 1, partType: 'MATERIAL', material: 'AN257-P3', subKit: 'FINISH' },
    { partNumber: 'COWL-10-03-L', nomenclature: 'SIDE HINGE', qtyRequired: 1, partType: 'MATERIAL', material: 'AN257-P3', subKit: 'FINISH' },
    { partNumber: 'COWL-10-03-R', nomenclature: 'SIDE HINGE', qtyRequired: 1, partType: 'MATERIAL', material: 'AN257-P3', subKit: 'FINISH' },
    { partNumber: 'C-RACK', nomenclature: '10" HANDLE RACK', qtyRequired: 2, partType: 'MANUFACTURED', material: 'VENDOR ITEM', subKit: 'FINISH' },
    { partNumber: 'F-1001S', nomenclature: 'COWL TOP HINGE PIN', qtyRequired: 2, partType: 'MATERIAL', material: 'SSP-060', subKit: 'FINISH' },
    { partNumber: 'F-1001T', nomenclature: 'COWL SIDE HINGE PIN', qtyRequired: 2, partType: 'MATERIAL', material: 'SSP-120', subKit: 'FINISH' },
    { partNumber: 'F-1001U', nomenclature: 'COWL BOT HINGE PIN', qtyRequired: 2, partType: 'MATERIAL', material: 'SSP-120', subKit: 'FINISH' },
    { partNumber: 'F-1001V', nomenclature: 'COWL PIN RETAINER', qtyRequired: 2, partType: 'MATERIAL', material: 'HINGE PIANO 1/8', subKit: 'FINISH' },
    { partNumber: 'F-1001Y', nomenclature: 'COWL UPPER PIN RETAINER', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'F-1001Z', nomenclature: 'FILLER PLATE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'F-10108A', nomenclature: 'SUPPORT BRACKET', qtyRequired: 1, partType: 'MANUFACTURED', material: '.032 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'F-10108B', nomenclature: 'SPLICE PLATE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.032 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'F-10108C', nomenclature: 'PLATE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.040 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'F-10109', nomenclature: 'LOUVER', qtyRequired: 2, partType: 'MANUFACTURED', material: '.020 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'J-11968-14', nomenclature: 'NOSE GEAR ELASTOMER', qtyRequired: 4, partType: 'MANUFACTURED', material: 'VENDOR ITEM', subKit: 'FINISH' },
    { partNumber: 'S-1001', nomenclature: 'GAP FILLER', qtyRequired: 2, partType: 'MATERIAL', material: 'AS3-063 X 2.56 X 4.05', subKit: 'FINISH' },
    { partNumber: 'S-1002', nomenclature: 'BACKING PLATE', qtyRequired: 2, partType: 'MATERIAL', material: 'AS3-063 X 1.25 X 1.93', subKit: 'FINISH' },
    { partNumber: 'S-601-1', nomenclature: 'SPINNER', qtyRequired: 1, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'S-602-1', nomenclature: 'SPINNER BACK PLATE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'S-602B', nomenclature: 'DOUBLER RING', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'S-603', nomenclature: 'SPINNER FRONT PLATE', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'SPRING-00003', nomenclature: 'COMP 1.400X2.25', qtyRequired: 1, partType: 'MANUFACTURED', material: 'MUSIC WIRE', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'U-00022', nomenclature: 'SPACER', qtyRequired: 2, partType: 'MANUFACTURED', material: '2024-T3', subKit: 'FINISH' },
    { partNumber: 'U-01407', nomenclature: 'PAD, ELASTOMER', qtyRequired: 1, partType: 'MANUFACTURED', material: '2024-T351', subKit: 'FINISH' },
    { partNumber: 'U-01420-1', nomenclature: 'CAP, LINK ASSEMBLY', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 OR 4140', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'U-1001-L-PC', nomenclature: 'MAIN GEAR LEG', qtyRequired: 1, partType: 'MANUFACTURED', material: '6150 STEEL', subKit: 'FINISH' },
    { partNumber: 'U-1001-R-PC', nomenclature: 'MAIN GEAR LEG', qtyRequired: 1, partType: 'MANUFACTURED', material: '6150 STEEL', subKit: 'FINISH' },
    { partNumber: 'U-1005', nomenclature: 'SPACER', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1545' },
    { partNumber: 'U-1008', nomenclature: 'SPACER', qtyRequired: 6, partType: 'MATERIAL', material: 'AT6-058 X 3/8', subKit: 'FINISH' },
    { partNumber: 'U-1010-L', nomenclature: 'MAIN WHEEL FAIRING BRACKET', qtyRequired: 1, partType: 'MANUFACTURED', material: '.125 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'U-1010-R', nomenclature: 'MAIN WHEEL FAIRING BRACKET', qtyRequired: 1, partType: 'MANUFACTURED', material: '.125 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'U-1013A', nomenclature: 'WHEEL FAIRING FRONT', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1013B', nomenclature: 'WHEEL FAIRING REAR', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1013C-L', nomenclature: 'NOSE WHEEL - FAIRING BRACKET', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'U-1013C-R', nomenclature: 'NOSE WHEEL - FAIRING BRACKET', qtyRequired: 1, partType: 'MANUFACTURED', material: '.063 2024-T3 ALCLAD', subKit: 'FINISH' },
    { partNumber: 'U-1017A', nomenclature: 'GEAR LEG FAIRING', qtyRequired: 2, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1017B', nomenclature: 'GEAR LEG FAIRING HINGE', qtyRequired: 2, partType: 'MATERIAL', material: 'HINGE PIANO 063', subKit: 'FINISH' },
    { partNumber: 'U-1018A', nomenclature: 'NOSE GEAR LEG FAIRING', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1018C', nomenclature: 'NOSE GEAR FAIRING HINGE', qtyRequired: 1, partType: 'MATERIAL', material: 'HINGE PIANO 063', subKit: 'FINISH' },
    { partNumber: 'U-1019-L', nomenclature: 'LOWER INTERSECTION FAIRING', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/RT CURE EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1019-R', nomenclature: 'LOWER INTERSECTION FAIRING', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/RT CURE EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1020-L', nomenclature: 'UPPER INTERSECTION FAIRING', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/RT CURE EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1020-R', nomenclature: 'UPPER INTERSECTION FAIRING', qtyRequired: 1, partType: 'MANUFACTURED', material: 'E-GLASS/RT CURE EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1021', nomenclature: 'SHOULDER BUSHING', qtyRequired: 8, partType: 'MANUFACTURED', material: 'WIE MAKE OR VENDOR ITEM', subKit: 'FINISH', bag: 'BAG 1546' },
    { partNumber: 'U-1024', nomenclature: 'STANDOFF', qtyRequired: 2, partType: 'MATERIAL', material: '2024-T351 BAR', subKit: 'FINISH' },
    { partNumber: 'U-1057A', nomenclature: 'WHEEL FAIRING FRONT', qtyRequired: 2, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'U-1057B', nomenclature: 'WHEEL FAIRING REAR', qtyRequired: 2, partType: 'MANUFACTURED', material: 'E-GLASS/EPOXY', subKit: 'FINISH' },
    { partNumber: 'VA-143', nomenclature: 'BUSHING', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1546' },
    { partNumber: 'VA-197', nomenclature: 'SPRING 5/8 X 2.5 COMPRESSION', qtyRequired: 2, partType: 'MANUFACTURED', material: '304 STAINLESS', subKit: 'FINISH', bag: 'BAG 1546' },
    { partNumber: 'VA-198', nomenclature: 'DOOR SEAL', qtyRequired: 2, partType: 'MATERIAL', material: 'RUBBER "P" SEAL', subKit: 'FINISH' },
    { partNumber: 'VENT SCAT 2X10', nomenclature: 'FWD HEATER HOSE', qtyRequired: 1, partType: 'MATERIAL', material: 'VENT SCAT 2" DIA.', subKit: 'FINISH' },
    { partNumber: 'VENT SCAT 2X54', nomenclature: 'AFT HEATER HOSE', qtyRequired: 1, partType: 'MATERIAL', material: 'VENT SCAT 2" DIA.', subKit: 'FINISH' },
    { partNumber: 'VENT SV-10', nomenclature: 'VENT FRESH AIR', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'WASHER-00017', nomenclature: '.375X.750X.090 STL', qtyRequired: 6, partType: 'MANUFACTURED', material: '4130', subKit: 'FINISH', bag: 'BAG 1542' },
    { partNumber: 'WD-00002', nomenclature: 'TORQUE TUBE ASSEMBLY, RECLINE', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'WD-00003-1', nomenclature: 'FRAME ASSEMBLY, SEAT BACK', qtyRequired: 2, partType: 'MANUFACTURED', material: 'N/A', subKit: 'FINISH' },
    { partNumber: 'WD-01001-D1-1', nomenclature: 'DYNA-1 ENGINE MOUNT', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'WD-1016-1', nomenclature: 'NOSE GEAR LINK ASSEMBLY', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'WD-1017-1-PC', nomenclature: 'NOSE GEAR LEG ASSEMBLY', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'WD-1018-L', nomenclature: 'CABIN HINGE FWD LEFT/ AFT RIGHT', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1548' },
    { partNumber: 'WD-1018-R', nomenclature: 'CABIN HINGE FWD RIGHT/ AFT LEFT', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1548' },
    { partNumber: 'WD-1019-L', nomenclature: 'DOOR HINGE FWD LEFT/ AFT RIGHT', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1548' },
    { partNumber: 'WD-1019-R', nomenclature: 'DOOR HINGE FWD RIGHT/ AFT LEFT', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH', bag: 'BAG 1548' },
    { partNumber: 'WD-1022-PC', nomenclature: 'DOOR HANDLE ASSEMBLY', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'WD-1023-PC', nomenclature: 'GAS STRUT ATTACH BRACKET', qtyRequired: 2, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },
    { partNumber: 'WD-1030', nomenclature: 'NOSE FORK', qtyRequired: 1, partType: 'MANUFACTURED', material: '6061-T6 ALUMINUM', subKit: 'FINISH' },
    { partNumber: 'WD-1031-PC', nomenclature: 'AXLE FLANGE', qtyRequired: 1, partType: 'MANUFACTURED', material: '4130 STEEL', subKit: 'FINISH' },

    // ── HARDWARE (from packing list bags) ────────────────────────────

    // BAG 540 — DOOR LATCH HWRE
    { partNumber: 'AS3-040X2 1/2X2 3/4', nomenclature: 'ALUM SHEET', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'BUSHING SB187-2', nomenclature: 'SNAP-IN 1/8ID 3/16OD', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES 31890', nomenclature: '#18-22WIRE/#8 RING', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES 36152', nomenclature: '#20 WIRE/#6 SCREW', qtyRequired: 3, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES 421-0107 CONNECTOR', nomenclature: 'MALE SLIP-ON CONN.', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES 421-0108 CONNECTOR', nomenclature: 'FEMALE SLIP-ON CONN.', qtyRequired: 10, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES RS 276-270', nomenclature: 'RED LED W/HOLDER', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'ES RS 49-496', nomenclature: 'MAGNET & SWITCH', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },
    { partNumber: 'MS21919DG4', nomenclature: 'CUSHION CLAMP 1/4', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 540' },

    // BAG 541 — DOOR LATCH HARDWARE
    { partNumber: 'AN3-3A', nomenclature: 'AN BOLT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'AN365-632A', nomenclature: 'NUT, STOP 6-32', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'AN365-832A', nomenclature: 'NUT, STOP 8-32', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'AN509-8R8', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'AN515-6R8', nomenclature: '6-32X1/2 PAN HEAD SCREW', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'K1000-3', nomenclature: 'PLATENUT 10-32 MS21047L3', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'NAS1149F0332P', nomenclature: 'REPLACES AN960-10L', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'NAS1149FN632P', nomenclature: 'REPLACES AN960-6', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },
    { partNumber: 'NAS1149FN832P', nomenclature: 'REPLACES AN960-8', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 541' },

    // BAG 1020 — BOLTS/SCREWS, 10 FRONT SEAT HWR
    { partNumber: 'AN3-5A', nomenclature: 'AN BOLT', qtyRequired: 16, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },
    { partNumber: 'AN3-6A', nomenclature: 'AN BOLT', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },
    { partNumber: 'AN4-13A', nomenclature: 'AN BOLT', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },
    { partNumber: 'AN4-4A', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },
    { partNumber: 'AN525-832R8', nomenclature: 'SCREW, WASHER HD', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },
    { partNumber: 'NAS1352-08-16P', nomenclature: 'SCREW, CAP, SOCKET HEAD', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1020' },

    // BAG 1021 — NUTS/WASH, 10 FRONT SEAT HWR
    { partNumber: 'AN365-1032', nomenclature: 'NUT, STOP', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'AN365-428', nomenclature: 'NUT, STOP 1/4-28', qtyRequired: 12, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'AN970-4', nomenclature: 'WASHER 1 1/8 OD', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'MS21042-08', nomenclature: '8-32 METAL LOCK NUT', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'MS21042-3', nomenclature: '10-32 METAL LOCK NUT', qtyRequired: 24, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'MS21042-4', nomenclature: '1/4-28 METAL LOCKNUT', qtyRequired: 16, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'MS35649-282', nomenclature: 'NUT HEX', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'NAS1149F0363P', nomenclature: 'REPLACES AN960-10', qtyRequired: 24, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'NAS1149F0463P', nomenclature: 'REPLACES AN960-416', qtyRequired: 16, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'WASHER-00025', nomenclature: 'PTFE .531x1.000x.010', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },
    { partNumber: 'WASHER-00026', nomenclature: 'PTFE .531x1.000x.015', qtyRequired: 12, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1021' },

    // BAG 1022 — SPRING/WASH, 10 FRONT SEAT HWR
    { partNumber: 'MS27039-4-13', nomenclature: 'SCREW PAN HD', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'NAS1149F0332P', nomenclature: 'REPLACES AN960-10L', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'NAS1149F0432P', nomenclature: 'REPLACES AN960-416L', qtyRequired: 16, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'NAS1149FN832P', nomenclature: 'REPLACES AN960-8', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'SPRING-00008', nomenclature: 'Exten .359x1.75', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'SPRING-00009', nomenclature: 'Comp .720x2.50', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },
    { partNumber: 'SPRING-00010', nomenclature: 'Comp .480x1.50', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1022' },

    // BAG 1023 — MISC HWR, 10 FRONT SEAT
    { partNumber: 'BEARING-00001', nomenclature: 'SELF LUBRICATING BEARING', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },
    { partNumber: 'BEARING-00002', nomenclature: 'SELF LUBRICATING BEARING', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },
    { partNumber: 'BUSH-ST.250X.499X.375', nomenclature: 'STEEL BUSHING', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },
    { partNumber: 'MS16562-33', nomenclature: 'ROLL PIN', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },
    { partNumber: 'MS16562-47', nomenclature: 'ROLL PIN', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },
    { partNumber: 'RIVET CR3213-4-2', nomenclature: 'CHERRY RIVET ROUND', qtyRequired: 86, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1023' },

    // BAG 1024 — SCREWS HWR, 10 FRONT SEAT
    { partNumber: 'MS27039-08-08', nomenclature: 'SCREW PAN HD', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS27039-1-11', nomenclature: 'SCREW PAN HD', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS27039-4-14', nomenclature: 'SCREW PAN HD', qtyRequired: 10, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS27039-4-17', nomenclature: 'SCREW PAN HD', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS27039-4-20', nomenclature: 'SCREW PAN HD', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS35206-226', nomenclature: 'SCREW PAN HD', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },
    { partNumber: 'MS35206-241', nomenclature: 'SCREW PAN HD', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1024' },

    // BAG 1232 — AN470AD4-5
    { partNumber: 'AN470AD4-5', nomenclature: 'UNIVERSAL HEAD RIVETS', qtyRequired: 0.040, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1232', unit: 'lb' },

    // BAG 1412 — AN470AD4-6
    { partNumber: 'AN470AD4-6', nomenclature: 'UNIVERSAL HEAD RIVETS', qtyRequired: 0.060, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1412', unit: 'lb' },

    // BAG 542 — SAFETY LATCH HWR
    { partNumber: 'AN3-12', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542' },
    { partNumber: 'AN310-3', nomenclature: 'NUT, CASTLE 3/16', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542' },
    { partNumber: 'AN426AD3-3.5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542', unit: 'lb' },
    { partNumber: 'C-1018', nomenclature: 'SAFETY LATCH', qtyRequired: 10, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542' },
    { partNumber: 'MS24665-132', nomenclature: 'COTTER PIN', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542' },
    { partNumber: 'NAS1149F0332P', nomenclature: 'REPLACES AN960-10L', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 542' },

    // BAG 543 — SAFETY LATCH HWR
    { partNumber: 'AN426AD4-12', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.020, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 543', unit: 'lb' },
    { partNumber: 'NAS1149F0363P', nomenclature: 'REPLACES AN960-10', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 543' },
    { partNumber: 'RIVET CCR-264SS-3-2', nomenclature: '3/32 FLUSH SS', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 543' },
    { partNumber: 'RIVET LP4-3', nomenclature: 'POP RIVET', qtyRequired: 30, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 543' },

    // BAG 1002 — MAGNET KIT
    { partNumber: 'HW-00011', nomenclature: 'SPHERICAL MAGNET', qtyRequired: 20, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1002' },
    { partNumber: 'WASHER 5610-18-31', nomenclature: '#8 NYLON FLAT RETAINING WASHER', qtyRequired: 20, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1002' },

    // BAG 1111 — AN426AD4-5
    { partNumber: 'AN426AD4-5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1111', unit: 'lb' },

    // BAG 1122 — POP RIVET CCR264SS3-2
    { partNumber: 'RIVET CCR-264SS-3-2', nomenclature: '3/32 FLUSH SS', qtyRequired: 12, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1122' },

    // BAG 1501 — AN426AD3-3.5
    { partNumber: 'AN426AD3-3.5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.040, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1501', unit: 'lb' },

    // BAG 1502 — AN426AD3-4
    { partNumber: 'AN426AD3-4', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.080, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1502', unit: 'lb' },

    // BAG 1510 — AN470AD3-4
    { partNumber: 'AN470AD3-4', nomenclature: 'UNIVERSAL HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1510', unit: 'lb' },

    // BAG 1512 — AN470AD4-5
    { partNumber: 'AN470AD4-5', nomenclature: 'UNIVERSAL HEAD RIVETS', qtyRequired: 0.020, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1512', unit: 'lb' },

    // BAG 1516 — RIVET LP4-3
    { partNumber: 'RIVET LP4-3', nomenclature: 'POP RIVET', qtyRequired: 36, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1516' },

    // BAG 1518 — AN3/AN5 BOLTS
    { partNumber: 'AN3-10A', nomenclature: 'AN BOLT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1518' },
    { partNumber: 'AN3-21A', nomenclature: 'AN BOLT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1518' },
    { partNumber: 'AN5-21A', nomenclature: 'AN BOLT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1518' },
    { partNumber: 'AN5-24A', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1518' },

    // BAG 1520 — AN4 BOLTS
    { partNumber: 'AN4-14A', nomenclature: 'AN BOLT', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1520' },
    { partNumber: 'AN4-15A', nomenclature: 'AN BOLT', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1520' },
    { partNumber: 'AN4-6A', nomenclature: 'AN BOLT', qtyRequired: 10, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1520' },
    { partNumber: 'AN4-7A', nomenclature: 'AN BOLT', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1520' },
    { partNumber: 'AN4H4A', nomenclature: 'AN BOLT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1520' },

    // BAG 1522 — AN6/AN7 BOLTS
    { partNumber: 'AN6-22A', nomenclature: 'AN BOLT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN6-23', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN6-23A', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN6-25A', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN6-65A', nomenclature: 'AN BOLT: RV-10/14 NOSE WHEEL', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN7-22', nomenclature: 'AN BOLT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },
    { partNumber: 'AN7-26', nomenclature: 'AN BOLT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1522' },

    // BAG 1523 — SCREWS 632/832
    { partNumber: 'AN507C632R8', nomenclature: 'SCREW, FLT HD SS', qtyRequired: 40, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1523' },
    { partNumber: 'AN507C832R8', nomenclature: 'SCREW, FLT HD SS', qtyRequired: 20, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1523' },

    // BAG 1524 — MISC. NUTS
    { partNumber: 'AN310-6', nomenclature: 'NUT, CASTLE 3/8', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1524' },
    { partNumber: 'AN310-7', nomenclature: 'NUT, CASTLE 7/16', qtyRequired: 3, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1524' },
    { partNumber: 'AN365-428', nomenclature: 'NUT, STOP 1/4-28', qtyRequired: 25, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1524' },
    { partNumber: 'AN365-524', nomenclature: '5/16-24 LOCK NUT', qtyRequired: 5, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1524' },
    { partNumber: 'AN365-624A', nomenclature: 'NUT, STOP 3/8-24', qtyRequired: 3, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1524' },

    // BAG 1525 — SCREWS: FLATHEAD
    { partNumber: 'AN509-10R11', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 22, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },
    { partNumber: 'AN509-10R13', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },
    { partNumber: 'AN509-10R14', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },
    { partNumber: 'AN509-10R16', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 20, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },
    { partNumber: 'AN509-8R14', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },
    { partNumber: 'AN509-8R8', nomenclature: 'SCREW, FLT HD STRUCT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1525' },

    // BAG 1526-1 — SCREWS SS 632/832/SMS
    { partNumber: 'AN526-8R12', nomenclature: 'SCREW, TRUSS HD', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1526-1' },
    { partNumber: 'AN526C632R8', nomenclature: 'SCREW, TRUSS HD SS', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1526-1' },
    { partNumber: 'AN526C832R8', nomenclature: 'SCREW, TRUSS HD SS', qtyRequired: 48, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1526-1' },
    { partNumber: 'SCREW #6X1/2 SS SMS', nomenclature: '100 DG FLT HD SS SMS', qtyRequired: 8, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1526-1' },

    // BAG 1527 — NUTS: 10-32
    { partNumber: 'AN365-1032', nomenclature: 'NUT, STOP', qtyRequired: 48, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1527' },
    { partNumber: 'MS21042-3', nomenclature: '10-32 METAL LOCK NUT', qtyRequired: 16, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1527' },

    // BAG 1528 — HOSE CLAMPS
    { partNumber: 'HW-00018', nomenclature: 'DYNAFLO #28 SS HOSE CLAMP 1.25-2.', qtyRequired: 5, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1528' },

    // BAG 1529 — MISC. LARGE WASHERS
    { partNumber: 'NAS1149F0432P', nomenclature: 'REPLACES AN960-416L', qtyRequired: 12, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },
    { partNumber: 'NAS1149F0463P', nomenclature: 'REPLACES AN960-416', qtyRequired: 40, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },
    { partNumber: 'NAS1149F0563P', nomenclature: 'REPLACES AN960-516', qtyRequired: 25, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },
    { partNumber: 'NAS1149F0632P', nomenclature: 'REPLACES AN960-616L', qtyRequired: 5, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },
    { partNumber: 'NAS1149F0663P', nomenclature: 'REPLACES AN960-616', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },
    { partNumber: 'NAS1149F0763P', nomenclature: 'REPLACES AN960-716', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1529' },

    // BAG 1530 — MISC. SMALL WASHERS
    { partNumber: 'NAS1149F0363P', nomenclature: 'REPLACES AN960-10', qtyRequired: 60, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1530' },
    { partNumber: 'NAS1149FN632P', nomenclature: 'REPLACES AN960-6', qtyRequired: 14, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1530' },
    { partNumber: 'NAS1149FN832P', nomenclature: 'REPLACES AN960-8', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1530' },

    // BAG 1531 — COWL CAMLOCKS
    { partNumber: 'HW 212-12', nomenclature: 'PLATENUT (COWL)', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1531' },
    { partNumber: 'HW 2600-3W', nomenclature: 'CAMLOCK FSTNR (COWL)', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1531' },
    { partNumber: 'HW 2600-LW', nomenclature: 'LOCKWASHER (COWL)', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1531' },

    // BAG 1532 — MISC PLATENUTS
    { partNumber: 'K1000-3', nomenclature: 'PLATENUT 10-32 MS21047L3', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1532' },
    { partNumber: 'MS21045-5', nomenclature: '5/16-24 METAL LCK NUT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1532' },

    // BAG 1533 — K1000-06 PLATENUTS
    { partNumber: 'K1000-06', nomenclature: '6-32 PLATENUT "FIGURE 8 SHAPE"', qtyRequired: 40, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1533' },

    // BAG 1534 — K1000-08 PLATENUTS
    { partNumber: 'K1000-08', nomenclature: 'PLATENUT 8-32 Kaynar', qtyRequired: 60, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1534' },

    // BAG 1535-1 — AXLE HWR
    { partNumber: 'HW LP24693C296', nomenclature: 'LOCKING 1/4-28 SCREW', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'MS15002-1', nomenclature: 'ZERK GREASE FITTING', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'MS16562-42', nomenclature: 'ROLL PIN', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'MS20392-1C15', nomenclature: 'CLEVIS PIN', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'MS21025-24', nomenclature: 'AXLE NUT 1.5"', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'MS24665-360', nomenclature: 'COTTER PIN MAIN GEAR', qtyRequired: 3, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },
    { partNumber: 'SCREW 3/8-24X1 3/4', nomenclature: 'SHCS 3/8-24x1 3/4', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1535-1' },

    // BAG 1536 — MISC. HI TEMP STOPNUT
    { partNumber: 'MS21042-06', nomenclature: '6-32 METAL LOCK NUT', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1536' },
    { partNumber: 'MS21042-08', nomenclature: '8-32 METAL LOCK NUT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1536' },
    { partNumber: 'MS21045-6', nomenclature: '3/8- LOCK NUT', qtyRequired: 7, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1536' },

    // BAG 1539-1 — COTTER PINS
    { partNumber: 'MS24665-153', nomenclature: 'COTTER PIN', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1539-1' },
    { partNumber: 'MS24665-208', nomenclature: 'COTTER PIN - CLEVIS', qtyRequired: 6, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1539-1' },
    { partNumber: 'MS24665-283', nomenclature: 'COTTER PIN 3/8 BOLT', qtyRequired: 5, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1539-1' },

    // BAG 1541 — NOSE GEAR HWR
    { partNumber: 'K2750-O-219', nomenclature: 'BELLVILLE WASHER', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1541' },
    { partNumber: 'NAS517-5-9', nomenclature: 'SCREW', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1541' },
    { partNumber: 'SCREW 5/16-24X3/4', nomenclature: 'SOCKET HEAD CAP SCREW', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1541' },

    // BAG 1542 — WASHERS
    { partNumber: 'WASHER 062 25783054', nomenclature: 'HARDENED GR. 8 WASHER', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1542' },
    { partNumber: 'WASHER 5610-18-31', nomenclature: '#8 NYLON FLAT RETAINING WASHER', qtyRequired: 40, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1542' },
    { partNumber: 'WASHER 5710-243-060', nomenclature: 'FOR RV-10 NOSE WHEEL', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1542' },
    { partNumber: 'WASHER LOCK 3/8', nomenclature: '3/8" LOCKWASHER', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1542' },

    // BAG 1545 — MISC. HARDWARE
    { partNumber: 'U-1002', nomenclature: 'ISOLATOR WASHER', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1545' },

    // BAG 1546 — MISC. HARDWARE
    { partNumber: 'AT6-058X3/8X4', nomenclature: 'ALUM TUBE (INCHES)', qtyRequired: 3, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'AT6-058X5/16X4', nomenclature: 'ALUM TUBE x 4"', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'BUSH-ST 375X750X1.563', nomenclature: 'STEEL BUSHING', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'MS21025-20', nomenclature: 'CASTLE NUT 1 1/4', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'ST4130-058X3/8X4', nomenclature: 'STEEL TUBE (INCHES)', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'U-00711', nomenclature: 'SPACER, AXLE', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'U-00712', nomenclature: 'AXLE NUT PIN', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },
    { partNumber: 'SR4130-1/2', nomenclature: '1/2" ROUND STEEL ROD', qtyRequired: 0.180, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1546' },

    // BAG 1548 — MISC. HARDWARE
    { partNumber: 'AB3-3/4X1 1/2X1.188', nomenclature: 'ALUM BAR', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1548' },

    // BAG 1934 — AN426AD3-5
    { partNumber: 'AN426AD3-5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 1934', unit: 'lb' },

    // BAG 805 — AN426AD3-4.5
    { partNumber: 'AN426AD3-4.5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.030, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 805', unit: 'lb' },

    // BAG 924-3 — C/S SPINNER HARDWARE
    { partNumber: 'AN426AD3-4', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3', unit: 'lb' },
    { partNumber: 'AN470AD4-5', nomenclature: 'UNIVERSAL HEAD RIVETS', qtyRequired: 0.020, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3', unit: 'lb' },
    { partNumber: 'AN4H4A', nomenclature: 'AN BOLT', qtyRequired: 4, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3' },
    { partNumber: 'AN526C832R8', nomenclature: 'SCREW, TRUSS HD SS', qtyRequired: 22, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3' },
    { partNumber: 'K1000-08', nomenclature: 'PLATENUT 8-32 Kaynar', qtyRequired: 22, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3' },
    { partNumber: 'NAS1149F0463P', nomenclature: 'REPLACES AN960-416', qtyRequired: 12, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3' },
    { partNumber: 'WASHER 5610-18-31', nomenclature: '#8 NYLON FLAT RETAINING WASHER', qtyRequired: 22, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 924-3' },

    // BAG 945 — ADDED SPINNER HWDRE
    { partNumber: 'AN426AD4-5', nomenclature: 'COUNTERSUNK HEAD RIVETS', qtyRequired: 0.010, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 945', unit: 'lb' },
    { partNumber: 'AN526C832R8', nomenclature: 'SCREW, TRUSS HD SS', qtyRequired: 24, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 945' },
    { partNumber: 'WASHER 5610-18-31', nomenclature: '#8 NYLON FLAT RETAINING WASHER', qtyRequired: 24, partType: 'HARDWARE', material: '', subKit: '', bag: 'BAG 945' },

    // ── STANDALONE PACKING LIST ITEMS (not in manifest, no bag) ──────

    { partNumber: '10 DOOR LATCH SYSTEM', nomenclature: 'WARNING LIGHT KIT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'DOC RV-10 DOOR LIGHT', nomenclature: 'WARNING LIGHT KIT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'ES HST-1/8 X 9 INCH', nomenclature: 'HEAT SHRINK', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'ES RLY-351', nomenclature: 'RV-10 DOOR LT RELAY', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "WIRE #18X20'", nomenclature: "WIRE M22759/16-18 TEFZELx 20'", qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 FIN SUB-KIT 1', nomenclature: 'MISC.PARTS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'AS3-063X5X10.469', nomenclature: 'ALUM SHEET', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'FBGLS.PARABEAM 9X30', nomenclature: 'FBGLS CLOTH 9"X30"', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 FIN SUB-KIT 2', nomenclature: 'MISC.PARTS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 FIN SUB-KIT 3', nomenclature: 'MISC.PARTS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 FIN SUB-KIT 5', nomenclature: 'MISC.PARTS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 FRONT SEAT KIT', nomenclature: 'PILOT AND COPILOT SEATS AND CUSHIONS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10 SAFETY LATCH KIT', nomenclature: 'SAFETY DOOR LATCH (2)', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'DOC 10 SAFETY LATCH', nomenclature: 'SECT 45A', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },

    { partNumber: '10A FINISH HARDWARE', nomenclature: 'HARDWARE BAGS', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: '10A PLANS FINISH', nomenclature: 'PLANS & MANUAL', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "AN257-P3X6'", nomenclature: "HINGE X 6'", qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'AS3-020X1/2X48', nomenclature: 'WINGTIP BACK STRIP', qtyRequired: 2, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'DOC SPINNER', nomenclature: 'DWG C-4', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "HINGE PIANO 063X3'", nomenclature: 'LEG FAIRING HINGE ALL', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "HINGE PIANO 063X6'", nomenclature: '063 PIANO HINGE', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "RUBBER DOOR SEALX25'", nomenclature: 'VA-198 DOOR SEAL', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "SSP-090X6'", nomenclature: 'STAINLESS STEEL PIN', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "SSP-120X6'", nomenclature: 'STAINLESS STEEL PIN', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: 'MANUAL-10 SECTION 49', nomenclature: 'FOR 10 FRONT SEAT KIT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
    { partNumber: "VENT SCAT 2X6'", nomenclature: 'SCAT TUBE X 6 FT', qtyRequired: 1, partType: 'HARDWARE', material: '', subKit: '' },
  ],

  bags: [
    { id: 'BAG 540', description: 'DOOR LATCH HWRE', contents: [
        { partNumber: 'AS3-040X2 1/2X2 3/4', qty: 1 },
        { partNumber: 'BUSHING SB187-2', qty: 2 },
        { partNumber: 'ES 31890', qty: 1 },
        { partNumber: 'ES 36152', qty: 3 },
        { partNumber: 'ES 421-0107 CONNECTOR', qty: 2 },
        { partNumber: 'ES 421-0108 CONNECTOR', qty: 10 },
        { partNumber: 'ES RS 276-270', qty: 2 },
        { partNumber: 'ES RS 49-496', qty: 4 },
        { partNumber: 'MS21919DG4', qty: 4 },
      ] },
    { id: 'BAG 541', description: 'DOOR LATCH HARDWARE', contents: [
        { partNumber: 'AN3-3A', qty: 1 },
        { partNumber: 'AN365-632A', qty: 2 },
        { partNumber: 'AN365-832A', qty: 2 },
        { partNumber: 'AN509-8R8', qty: 2 },
        { partNumber: 'AN515-6R8', qty: 2 },
        { partNumber: 'K1000-3', qty: 1 },
        { partNumber: 'NAS1149F0332P', qty: 1 },
        { partNumber: 'NAS1149FN632P', qty: 2 },
        { partNumber: 'NAS1149FN832P', qty: 2 },
      ] },
    { id: 'BAG 1020', description: 'BOLTS/SCREWS, 10 FRONT SEAT HWR', contents: [
        { partNumber: 'AN3-5A', qty: 16 },
        { partNumber: 'AN3-6A', qty: 8 },
        { partNumber: 'AN4-13A', qty: 8 },
        { partNumber: 'AN4-4A', qty: 2 },
        { partNumber: 'AN525-832R8', qty: 8 },
        { partNumber: 'NAS1352-08-16P', qty: 2 },
      ] },
    { id: 'BAG 1021', description: 'NUTS/WASH, 10 FRONT SEAT HWR', contents: [
        { partNumber: 'AN365-1032', qty: 8 },
        { partNumber: 'AN365-428', qty: 12 },
        { partNumber: 'AN970-4', qty: 6 },
        { partNumber: 'MS21042-08', qty: 8 },
        { partNumber: 'MS21042-3', qty: 24 },
        { partNumber: 'MS21042-4', qty: 16 },
        { partNumber: 'MS35649-282', qty: 2 },
        { partNumber: 'NAS1149F0363P', qty: 24 },
        { partNumber: 'NAS1149F0463P', qty: 16 },
        { partNumber: 'WASHER-00025', qty: 8 },
        { partNumber: 'WASHER-00026', qty: 12 },
      ] },
    { id: 'BAG 1022', description: 'SPRING/WASH, 10 FRONT SEAT HWR', contents: [
        { partNumber: 'CA-10003P', qty: 2 },
        { partNumber: 'MS27039-4-13', qty: 4 },
        { partNumber: 'NAS1149F0332P', qty: 8 },
        { partNumber: 'NAS1149F0432P', qty: 16 },
        { partNumber: 'NAS1149FN832P', qty: 8 },
        { partNumber: 'SPRING-00008', qty: 2 },
        { partNumber: 'SPRING-00009', qty: 2 },
        { partNumber: 'SPRING-00010', qty: 2 },
      ] },
    { id: 'BAG 1023', description: 'MISC HWR, 10 FRONT SEAT', contents: [
        { partNumber: 'BEARING-00001', qty: 4 },
        { partNumber: 'BEARING-00002', qty: 8 },
        { partNumber: 'BUSH-ST.250X.499X.375', qty: 8 },
        { partNumber: 'CA-10003T', qty: 2 },
        { partNumber: 'MS16562-33', qty: 2 },
        { partNumber: 'MS16562-47', qty: 2 },
        { partNumber: 'RIVET CR3213-4-2', qty: 86 },
      ] },
    { id: 'BAG 1024', description: 'SCREWS HWR, 10 FRONT SEAT', contents: [
        { partNumber: 'MS27039-08-08', qty: 2 },
        { partNumber: 'MS27039-1-11', qty: 8 },
        { partNumber: 'MS27039-4-14', qty: 10 },
        { partNumber: 'MS27039-4-17', qty: 4 },
        { partNumber: 'MS27039-4-20', qty: 2 },
        { partNumber: 'MS35206-226', qty: 8 },
        { partNumber: 'MS35206-241', qty: 4 },
      ] },
    { id: 'BAG 1025', description: 'HANDLE L/R, 10 FRONT SEAT', contents: [{ partNumber: 'CA-10003U', qty: 2 }] },
    { id: 'BAG 1232', description: 'AN470AD4-5', contents: [{ partNumber: 'AN470AD4-5', qty: 0.04 }] },
    { id: 'BAG 1412', description: 'AN470AD4-6', contents: [{ partNumber: 'AN470AD4-6', qty: 0.06 }] },
    { id: 'BAG 542', description: 'SAFETY LATCH HWR', contents: [
        { partNumber: 'AN3-12', qty: 2 },
        { partNumber: 'AN310-3', qty: 2 },
        { partNumber: 'AN426AD3-3.5', qty: 0.01 },
        { partNumber: 'C-1018', qty: 10 },
        { partNumber: 'C-1019', qty: 2 },
        { partNumber: 'MS24665-132', qty: 2 },
        { partNumber: 'NAS1149F0332P', qty: 4 },
      ] },
    { id: 'BAG 543', description: 'SAFETY LATCH HWR', contents: [
        { partNumber: 'AN426AD4-12', qty: 0.02 },
        { partNumber: 'C-1020', qty: 1 },
        { partNumber: 'NAS1149F0363P', qty: 4 },
        { partNumber: 'RIVET CCR-264SS-3-2', qty: 8 },
        { partNumber: 'RIVET LP4-3', qty: 30 },
      ] },
    { id: 'BAG 1002', description: 'MAGNET KIT', contents: [{ partNumber: 'HW-00011', qty: 20 }, { partNumber: 'WASHER 5610-18-31', qty: 20 }] },
    { id: 'BAG 1111', description: 'AN426AD4-5', contents: [{ partNumber: 'AN426AD4-5', qty: 0.01 }] },
    { id: 'BAG 1122', description: 'POP RIVET CCR264SS3-2', contents: [{ partNumber: 'RIVET CCR-264SS-3-2', qty: 12 }] },
    { id: 'BAG 1501', description: 'AN426AD3-3.5', contents: [{ partNumber: 'AN426AD3-3.5', qty: 0.04 }] },
    { id: 'BAG 1502', description: 'AN426AD3-4', contents: [{ partNumber: 'AN426AD3-4', qty: 0.08 }] },
    { id: 'BAG 1510', description: 'AN470AD3-4', contents: [{ partNumber: 'AN470AD3-4', qty: 0.01 }] },
    { id: 'BAG 1512', description: 'AN470AD4-5', contents: [{ partNumber: 'AN470AD4-5', qty: 0.02 }] },
    { id: 'BAG 1516', description: 'RIVET LP4-3', contents: [{ partNumber: 'RIVET LP4-3', qty: 36 }] },
    { id: 'BAG 1518', description: 'AN3/AN5 BOLTS', contents: [
        { partNumber: 'AN3-10A', qty: 4 },
        { partNumber: 'AN3-21A', qty: 4 },
        { partNumber: 'AN5-21A', qty: 1 },
        { partNumber: 'AN5-24A', qty: 2 },
      ] },
    { id: 'BAG 1520', description: 'AN4 BOLTS', contents: [
        { partNumber: 'AN4-14A', qty: 6 },
        { partNumber: 'AN4-15A', qty: 6 },
        { partNumber: 'AN4-6A', qty: 10 },
        { partNumber: 'AN4-7A', qty: 6 },
        { partNumber: 'AN4H4A', qty: 4 },
      ] },
    { id: 'BAG 1522', description: 'AN6/AN7 BOLTS', contents: [
        { partNumber: 'AN6-22A', qty: 4 },
        { partNumber: 'AN6-23', qty: 2 },
        { partNumber: 'AN6-23A', qty: 2 },
        { partNumber: 'AN6-25A', qty: 2 },
        { partNumber: 'AN6-65A', qty: 1 },
        { partNumber: 'AN7-22', qty: 2 },
        { partNumber: 'AN7-26', qty: 1 },
      ] },
    { id: 'BAG 1523', description: 'SCREWS 632/832', contents: [{ partNumber: 'AN507C632R8', qty: 40 }, { partNumber: 'AN507C832R8', qty: 20 }] },
    { id: 'BAG 1524', description: 'MISC. NUTS', contents: [
        { partNumber: 'AN310-6', qty: 2 },
        { partNumber: 'AN310-7', qty: 3 },
        { partNumber: 'AN365-428', qty: 25 },
        { partNumber: 'AN365-524', qty: 5 },
        { partNumber: 'AN365-624A', qty: 3 },
      ] },
    { id: 'BAG 1525', description: 'SCREWS: FLATHEAD', contents: [
        { partNumber: 'AN509-10R11', qty: 22 },
        { partNumber: 'AN509-10R13', qty: 8 },
        { partNumber: 'AN509-10R14', qty: 8 },
        { partNumber: 'AN509-10R16', qty: 20 },
        { partNumber: 'AN509-8R14', qty: 2 },
        { partNumber: 'AN509-8R8', qty: 2 },
      ] },
    { id: 'BAG 1526-1', description: 'SCREWS SS 632/832/SMS', contents: [
        { partNumber: 'AN526-8R12', qty: 2 },
        { partNumber: 'AN526C632R8', qty: 4 },
        { partNumber: 'AN526C832R8', qty: 48 },
        { partNumber: 'SCREW #6X1/2 SS SMS', qty: 8 },
      ] },
    { id: 'BAG 1527', description: 'NUTS: 10-32', contents: [{ partNumber: 'AN365-1032', qty: 48 }, { partNumber: 'MS21042-3', qty: 16 }] },
    { id: 'BAG 1528', description: 'HOSE CLAMPS', contents: [{ partNumber: 'HW-00018', qty: 5 }] },
    { id: 'BAG 1529', description: 'MISC. LARGE WASHERS', contents: [
        { partNumber: 'NAS1149F0432P', qty: 12 },
        { partNumber: 'NAS1149F0463P', qty: 40 },
        { partNumber: 'NAS1149F0563P', qty: 25 },
        { partNumber: 'NAS1149F0632P', qty: 5 },
        { partNumber: 'NAS1149F0663P', qty: 6 },
        { partNumber: 'NAS1149F0763P', qty: 4 },
      ] },
    { id: 'BAG 1530', description: 'MISC. SMALL WASHERS', contents: [{ partNumber: 'NAS1149F0363P', qty: 60 }, { partNumber: 'NAS1149FN632P', qty: 14 }, { partNumber: 'NAS1149FN832P', qty: 2 }] },
    { id: 'BAG 1531', description: 'COWL CAMLOCKS', contents: [{ partNumber: 'HW 212-12', qty: 2 }, { partNumber: 'HW 2600-3W', qty: 2 }, { partNumber: 'HW 2600-LW', qty: 2 }] },
    { id: 'BAG 1532', description: 'MISC PLATENUTS', contents: [{ partNumber: 'K1000-3', qty: 4 }, { partNumber: 'MS21045-5', qty: 1 }] },
    { id: 'BAG 1533', description: 'K1000-06 PLATENUTS', contents: [{ partNumber: 'K1000-06', qty: 40 }] },
    { id: 'BAG 1534', description: 'K1000-08 PLATENUTS', contents: [{ partNumber: 'K1000-08', qty: 60 }] },
    { id: 'BAG 1535-1', description: 'AXLE HWR', contents: [
        { partNumber: 'HW LP24693C296', qty: 2 },
        { partNumber: 'MS15002-1', qty: 1 },
        { partNumber: 'MS16562-42', qty: 4 },
        { partNumber: 'MS20392-1C15', qty: 4 },
        { partNumber: 'MS21025-24', qty: 1 },
        { partNumber: 'MS24665-360', qty: 3 },
        { partNumber: 'SCREW 3/8-24X1 3/4', qty: 2 },
      ] },
    { id: 'BAG 1536', description: 'MISC. HI TEMP STOPNUT', contents: [{ partNumber: 'MS21042-06', qty: 2 }, { partNumber: 'MS21042-08', qty: 4 }, { partNumber: 'MS21045-6', qty: 7 }] },
    { id: 'BAG 1539-1', description: 'COTTER PINS', contents: [{ partNumber: 'MS24665-153', qty: 2 }, { partNumber: 'MS24665-208', qty: 6 }, { partNumber: 'MS24665-283', qty: 5 }] },
    { id: 'BAG 1541', description: 'NOSE GEAR HWR', contents: [{ partNumber: 'K2750-O-219', qty: 2 }, { partNumber: 'NAS517-5-9', qty: 2 }, { partNumber: 'SCREW 5/16-24X3/4', qty: 2 }] },
    { id: 'BAG 1542', description: 'WASHERS', contents: [
        { partNumber: 'WASHER 062 25783054', qty: 2 },
        { partNumber: 'WASHER 5610-18-31', qty: 40 },
        { partNumber: 'WASHER 5710-243-060', qty: 1 },
        { partNumber: 'WASHER LOCK 3/8', qty: 2 },
        { partNumber: 'WASHER-00017', qty: 6 },
      ] },
    { id: 'BAG 1545', description: 'MISC. HARDWARE', contents: [
        { partNumber: 'BUSH-F-ST438X750X1.32', qty: 2 },
        { partNumber: 'C-1006A', qty: 2 },
        { partNumber: 'C-1006B', qty: 2 },
        { partNumber: 'C-1006C', qty: 2 },
        { partNumber: 'C-1006D', qty: 2 },
        { partNumber: 'C-1014', qty: 2 },
        { partNumber: 'F-1001Y', qty: 1 },
        { partNumber: 'F-1001Z', qty: 1 },
        { partNumber: 'SPRING-00003', qty: 1 },
        { partNumber: 'U-01420-1', qty: 1 },
        { partNumber: 'U-1002', qty: 2 },
        { partNumber: 'U-1005', qty: 2 },
      ] },
    { id: 'BAG 1546', description: 'MISC. HARDWARE', contents: [
        { partNumber: 'AT6-058X3/8X4', qty: 3 },
        { partNumber: 'AT6-058X5/16X4', qty: 2 },
        { partNumber: 'BUSH-ST 375X750X1.563', qty: 2 },
        { partNumber: 'C-1007', qty: 2 },
        { partNumber: 'C-656', qty: 2 },
        { partNumber: 'MS21025-20', qty: 1 },
        { partNumber: 'ST4130-058X3/8X4', qty: 1 },
        { partNumber: 'U-00711', qty: 1 },
        { partNumber: 'U-00712', qty: 1 },
        { partNumber: 'U-1021', qty: 8 },
        { partNumber: 'SR4130-1/2', qty: 0.18 },
        { partNumber: 'VA-143', qty: 1 },
        { partNumber: 'VA-197', qty: 2 },
      ] },
    { id: 'BAG 1547', description: 'MISC. HARDWARE', contents: [
        { partNumber: 'C-1009', qty: 2 },
        { partNumber: 'C-1010', qty: 4 },
        { partNumber: 'C-1013', qty: 2 },
        { partNumber: 'C-1015', qty: 2 },
        { partNumber: 'C-1017', qty: 2 },
      ] },
    { id: 'BAG 1548', description: 'MISC. HARDWARE', contents: [
        { partNumber: 'AB3-3/4X1 1/2X1.188', qty: 2 },
        { partNumber: 'WD-1018-L', qty: 2 },
        { partNumber: 'WD-1018-R', qty: 2 },
        { partNumber: 'WD-1019-L', qty: 2 },
        { partNumber: 'WD-1019-R', qty: 2 },
      ] },
    { id: 'BAG 1934', description: 'AN426AD3-5', contents: [{ partNumber: 'AN426AD3-5', qty: 0.01 }] },
    { id: 'BAG 805', description: 'AN426AD3-4.5', contents: [{ partNumber: 'AN426AD3-4.5', qty: 0.03 }] },
    { id: 'BAG 924-3', description: 'C/S SPINNER HARDWARE', contents: [
        { partNumber: 'AN426AD3-4', qty: 0.01 },
        { partNumber: 'AN470AD4-5', qty: 0.02 },
        { partNumber: 'AN4H4A', qty: 4 },
        { partNumber: 'AN526C832R8', qty: 22 },
        { partNumber: 'K1000-08', qty: 22 },
        { partNumber: 'NAS1149F0463P', qty: 12 },
        { partNumber: 'WASHER 5610-18-31', qty: 22 },
      ] },
    { id: 'BAG 945', description: 'ADDED SPINNER HWDRE', contents: [{ partNumber: 'AN426AD4-5', qty: 0.01 }, { partNumber: 'AN526C832R8', qty: 24 }, { partNumber: 'WASHER 5610-18-31', qty: 24 }] },
  ],
};
